# -*- coding: utf-8 -*-
"""understat.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mJF0AvgtkXLhpYPajlK-96tRUNx3paT
"""

!pip install understatapi --quiet

!pip install streamlit --quiet

#!streamlit run understat.py

import understatapi
import pandas as pd
import streamlit as st
import os

cwd = os.getcwd()
print(cwd)

client = understatapi.UnderstatClient()

league_op = st.selectbox("Select a league", client.player(player = "11094").leagues, index=None)
league_data = client.league(league_op).get_match_data(season = "2024")

data = client.league(league = "EPL").get_team_data(season = "2024")

client.player(player = "11094").leagues

pd.json_normalize(client.team(team= "Manchester_United").get_match_data(season = "2024")).head()

pd.json_normalize(client.team(team= "Manchester_United").get_player_data(season = "2024")).head()

pd.json_normalize(client.player(player = "10552").get_match_data()).head()

pd.json_normalize(client.player(player = "10552").get_season_data()).head()